# Generated by Django 6.0.6 on 2026-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.CharField(max_length=20)),
                ('eaddr', models.CharField(max_length=50)),
            ],
        ),
    ]
